### ISSUE TITLE
Dialog rollback

### ISSUE THREAD

**Issue by lucasaabueno** [eduardotkoller/convForm#13]
Hi!
First of all, great plugin, really easy to implement;
My only issue, is it possible to rollback to a previous dialog without reloading the entire chatbot?
Like, recall the last select before the fork.

Thx!
Lucas.

**Comment by eduardotkoller** [comment]
Hello Lucas,

It is possible but it is not built in the plugin, so you would have to do it manually.

The way the plugin works is using a linked list of states, with each state being a question and some properties. If you get the reference for the question you want to go back to, and change the next question pointer to this one, you are essentially rollbacking, but you need to change the pointer again or you will be stuck in a loop.

**Comment by fas3r** [comment]
Would you mind to Provide an example please ?

**Comment by eduardotkoller** [comment]
As some people are asking for something on a similar fashion, in the last commit I changed the code so the callback functions can be used for any type of question, not just selects, and the functions are called with the ConvState object being passed as a parameter, so you can now interact better with the conversation states. I added a rollback example in the conversation, that uses these functions to store a state and rollback to it in any moment later, and restore the original state order to get out of the loop.


	var rollbackTo = false;	
	var originalState = false;
	function storeState(stateWrapper) {
		rollbackTo = stateWrapper.current;
	}
	function rollback(stateWrapper) {
		if(rollbackTo!=false) {
			if(originalState==false) {
				originalState = stateWrapper.current.next;
			}
			stateWrapper.current.next = rollbackTo;
		}
	}
	function restore(stateWrapper) {
		stateWrapper.current.next = originalState;
	}

**Comment by lucasaabueno** [comment]
Hi Eduardo,
Thx for the rapid response,
About the callback functions,
Is it possible to link them to a button?
I want to have a 'Voltar' button on the footer,
I modified the storeState to record the previous states in a array,
but i haven't found a way to link the rollback since the callback method defines the 'stateWrapper' internally.
I've tried to set the convForm as an object as per the docs (var convForm = $('.conv-form-wrapper').convform("Write here...");) but the convForm forms when the page is loaded and prompting this returns (Uncaught TypeError: Cannot read property 'split' of undefined);
Any thoughts?

Thanks, Lucas.

**Comment by eduardotkoller** [comment]
Hi Lucas,
I tested it by defining a function after defining the convForm variable like in the example, and binding it to a button, and it works fine when I click the button.

Can you tell me at which line is the error occurring? Split is a string function so something that should be a string is not. Maybe you are forgetting a conv-question attribute in some input?

**Comment by lucasaabueno** [comment]
I've just included the plugin.js and created the chatbot on html (<div id="chat" class="conv-form-wrapper"><form action="" method="GET" class="hidden">),
As the page loads, the bot forms automatically, without any calls,
I've bind the convForm object creation to the modal show event;
This is what i get on console upon loading the page and then trying to open the modal:

```
ConvState {form: r.fn.init(1), wrapper: r.fn.init(1), current: SingleConvState, answers: {…}, scrollDown: ƒ}
jquery.convform.js:199 Uncaught TypeError: Cannot read property 'split' of undefined
    at HTMLTextAreaElement.<anonymous> (jquery.convform.js:199)
    at jquery.min.js:2
    at Function.map (jquery.min.js:2)
    at r.fn.init.map (jquery.min.js:2)
    at r.fn.init.$.fn.convform (jquery.convform.js:191)
    at HTMLDivElement.<anonymous> (index.js:89)
    at HTMLDivElement.dispatch (jquery.min.js:3)
    at HTMLDivElement.q.handle (jquery.min.js:3)
    at Object.trigger (jquery.min.js:4)
    at HTMLDivElement.<anonymous> (jquery.min.js:4)
```

Thx, Lucas

**Comment by eduardotkoller** [comment]
Hmm line 199 assumes that you have a conv-question attribute so if you have any input that doesn't have this attribute, or its empty or not a string, the split method will not work. Can you check if this is the case?

**Comment by lucasaabueno** [comment]
I've checked my code and every question has the conv-question;
What bugs me is that it works normally when i just load the plugin,
Maybe it's because the convForm already formed?

**Comment by eduardotkoller** [comment]
Hmm, maybe. Try removing the class 'conv-form-wrapper' and call the convForm plugin with another class, like 
`var convFormObject = $('div.my-conv-form-wrapper').convForm('Write here...');`

**Comment by lucasaabueno** [comment]
I've renamed the div to 'convForm' and it did the trick in which it's now possible to create the convForm calling the command;
But, on page load i get the following error: 
```
jquery.min.js:2 jQuery.Deferred exception: Cannot read property 'questions' of undefined TypeError: Cannot read property 'questions' of undefined
    at ConvState.printQuestion (http://skywalkersistemas.com.br/SMR/javascript/jquery.convform.js:38:40)
    at r.fn.init.$.fn.convform (http://skywalkersistemas.com.br/SMR/javascript/jquery.convform.js:254:15)
    at HTMLDocument.<anonymous> (http://skywalkersistemas.com.br/SMR/javascript/jquery.convform.js:395:44)
    at j (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:29999)
    at k (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:30313) undefined
r.Deferred.exceptionHook @ jquery.min.js:2
k @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
S @ jquery.min.js:3
jquery.min.js:2 Uncaught TypeError: Cannot read property 'questions' of undefined
    at ConvState.printQuestion (jquery.convform.js:38)
    at r.fn.init.$.fn.convform (jquery.convform.js:254)
    at HTMLDocument.<anonymous> (jquery.convform.js:395)
    at j (jquery.min.js:2)
    at k (jquery.min.js:2)
```
And when the convform is created it jumps the first question;

**Comment by eduardotkoller** [comment]
@lucasaabueno I think I fixed this last error (when plugin tried to initialize on a selector that doesn't exist). Can you see if the error is gone now?

**Comment by fas3r** [comment]
Hello, 

I recall that I got similar issue, I removed the following and the error disappear. 

https://github.com/eduardotkoller/convForm/blob/59e488fd0dcd74403ae6c3d83a0971d427ad8342/dist/jquery.convform.js#L398-L402

That's because you probably try to initiate the plugin with a different class and by default the plugin is looking for a element with conv-form-wrapper class in the DOM.


BR,

**Comment by lucasaabueno** [comment]
So, i did as fas3r suggested and removed that part of the plugin code and it did work as far as being able to correctly initialize the convForm and return the usable object, but, when i bind the restore function to the 'Back' button nothing happens, if i type something in the awnser field and submit it however, the plugin triggers the rollback.
I think that there is a trigger missing somewhere

**Comment by eduardotkoller** [comment]
I don't use any custom triggers in the plugin. Are you sure you aren't binding the restore function as a callback to the first question? Also, are you storing the last question at every question?

The restore function I used in the example uses other variables that needs to be initialized before calling it (in that case, I call the storeState function to store the state I want to rollback to in the rollbackTo variable). 

Using a "back" button would need a more complicated logic. If you want the button to just rollback to the last question whenever the user clicks its, you have to:

1. store the last question somewhere and update the variable for every question that you pass through, for example using the storeState function I used in the example, as a callback for every question.
2. in the restore function, you need not only to change the "next" question in the list to the last one stored, but you need also to change the next question to the original "next" question, after you rolled back to the last one, or you will stand in an endless loop. As the callback function is called before changing to the next state, you can't do both at the same time, so I would recommend changing the storeState function that you must call at every function to check if the button was pressed (add a variable to the mix and change it when you call the button), and if so you change the "next's next" to the original flow.

 I don't know if I was clear enough, as this is kinda hard to explain, but please let me know. I can't try it right now, but I will later.

**Comment by abhi09cse02** [comment]
I want to create A Smart Chat Bot From An Html Form - convForm by referring given url with autocomplete feature to suggest city/town name. How can i use it? Please suggest

https://eduardotkoller.github.io/convForm/

**Comment by anithats1988** [comment]
I want to create a chatbot with auto suggest places from google API. Any help would be appreciated.

**Comment by anithats1988** [comment]
required placeholder is not working in ConvForm

**Comment by Gigiart** [comment]
> So, i did as fas3r suggested and removed that part of the plugin code and it did work as far as being able to correctly initialize the convForm and return the usable object, but, when i bind the restore function to the 'Back' button nothing happens, if i type something in the awnser field and submit it however, the plugin triggers the rollback.
> I think that there is a trigger missing somewhere

Did you get this fixed? Please add your code here if you successfully implemented this.

**Comment by vishakraman** [comment]
> I don't use any custom triggers in the plugin. Are you sure you aren't binding the restore function as a callback to the first question? Also, are you storing the last question at every question?
> 
> The restore function I used in the example uses other variables that needs to be initialized before calling it (in that case, I call the storeState function to store the state I want to rollback to in the rollbackTo variable).
> 
> Using a "back" button would need a more complicated logic. If you want the button to just rollback to the last question whenever the user clicks its, you have to:
> 
> 1. store the last question somewhere and update the variable for every question that you pass through, for example using the storeState function I used in the example, as a callback for every question.
> 2. in the restore function, you need not only to change the "next" question in the list to the last one stored, but you need also to change the next question to the original "nu you call the button), and if so you change the "next's next" to the original flow.
> 
> I don't know if I was clear enough, as this is kinda hard to explain, but please let me know. I can't try it right now, but I will later.

Is this feature implemented yet?
